// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test1.proto

#include "test1.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace test {
class struExampleDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<struExample>
      _instance;
} _struExample_default_instance_;
class struExamples_MEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<struExamples_MEntry_DoNotUse>
      _instance;
} _struExamples_MEntry_DoNotUse_default_instance_;
class struExamplesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<struExamples>
      _instance;
} _struExamples_default_instance_;
}  // namespace test
namespace protobuf_test1_2eproto {
void InitDefaultsstruExampleImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::test::_struExample_default_instance_;
    new (ptr) ::test::struExample();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::test::struExample::InitAsDefaultInstance();
}

void InitDefaultsstruExample() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsstruExampleImpl);
}

void InitDefaultsstruExamples_MEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_test1_2eproto::InitDefaultsstruExample();
  {
    void* ptr = &::test::_struExamples_MEntry_DoNotUse_default_instance_;
    new (ptr) ::test::struExamples_MEntry_DoNotUse();
  }
  ::test::struExamples_MEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsstruExamples_MEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsstruExamples_MEntry_DoNotUseImpl);
}

void InitDefaultsstruExamplesImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_test1_2eproto::InitDefaultsstruExample();
  protobuf_test1_2eproto::InitDefaultsstruExamples_MEntry_DoNotUse();
  {
    void* ptr = &::test::_struExamples_default_instance_;
    new (ptr) ::test::struExamples();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::test::struExamples::InitAsDefaultInstance();
}

void InitDefaultsstruExamples() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsstruExamplesImpl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExample, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExample, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExample, str_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExample, f_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExample, db_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExamples_MEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExamples_MEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExamples_MEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExamples_MEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExamples, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExamples, v_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::struExamples, m_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::test::struExample)},
  { 9, 16, sizeof(::test::struExamples_MEntry_DoNotUse)},
  { 18, -1, sizeof(::test::struExamples)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_struExample_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_struExamples_MEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_struExamples_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "test1.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013test1.proto\022\004test\"=\n\013struExample\022\n\n\002id"
      "\030\001 \001(\r\022\013\n\003str\030\002 \001(\t\022\t\n\001f\030\003 \001(\002\022\n\n\002db\030\004 \001"
      "(\001\"\217\001\n\014struExamples\022\034\n\001v\030\001 \003(\0132\021.test.st"
      "ruExample\022$\n\001m\030\002 \003(\0132\031.test.struExamples"
      ".MEntry\032;\n\006MEntry\022\013\n\003key\030\001 \001(\005\022 \n\005value\030"
      "\002 \001(\0132\021.test.struExample:\0028\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 236);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "test1.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_test1_2eproto
namespace test {

// ===================================================================

void struExample::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int struExample::kIdFieldNumber;
const int struExample::kStrFieldNumber;
const int struExample::kFFieldNumber;
const int struExample::kDbFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

struExample::struExample()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_test1_2eproto::InitDefaultsstruExample();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.struExample)
}
struExample::struExample(const struExample& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.str().size() > 0) {
    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&db_) -
    reinterpret_cast<char*>(&id_)) + sizeof(db_));
  // @@protoc_insertion_point(copy_constructor:test.struExample)
}

void struExample::SharedCtor() {
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&db_) -
      reinterpret_cast<char*>(&id_)) + sizeof(db_));
  _cached_size_ = 0;
}

struExample::~struExample() {
  // @@protoc_insertion_point(destructor:test.struExample)
  SharedDtor();
}

void struExample::SharedDtor() {
  str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void struExample::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* struExample::descriptor() {
  ::protobuf_test1_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test1_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const struExample& struExample::default_instance() {
  ::protobuf_test1_2eproto::InitDefaultsstruExample();
  return *internal_default_instance();
}

struExample* struExample::New(::google::protobuf::Arena* arena) const {
  struExample* n = new struExample;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void struExample::Clear() {
// @@protoc_insertion_point(message_clear_start:test.struExample)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&db_) -
      reinterpret_cast<char*>(&id_)) + sizeof(db_));
  _internal_metadata_.Clear();
}

bool struExample::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.struExample)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string str = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_str()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->str().data(), static_cast<int>(this->str().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "test.struExample.str"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float f = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &f_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double db = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &db_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.struExample)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.struExample)
  return false;
#undef DO_
}

void struExample::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.struExample)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // string str = 2;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), static_cast<int>(this->str().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "test.struExample.str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->str(), output);
  }

  // float f = 3;
  if (this->f() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->f(), output);
  }

  // double db = 4;
  if (this->db() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->db(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:test.struExample)
}

::google::protobuf::uint8* struExample::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:test.struExample)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // string str = 2;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), static_cast<int>(this->str().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "test.struExample.str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->str(), target);
  }

  // float f = 3;
  if (this->f() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->f(), target);
  }

  // double db = 4;
  if (this->db() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->db(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.struExample)
  return target;
}

size_t struExample::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.struExample)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string str = 2;
  if (this->str().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->str());
  }

  // uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  // float f = 3;
  if (this->f() != 0) {
    total_size += 1 + 4;
  }

  // double db = 4;
  if (this->db() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void struExample::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.struExample)
  GOOGLE_DCHECK_NE(&from, this);
  const struExample* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const struExample>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.struExample)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.struExample)
    MergeFrom(*source);
  }
}

void struExample::MergeFrom(const struExample& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.struExample)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.str().size() > 0) {

    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.f() != 0) {
    set_f(from.f());
  }
  if (from.db() != 0) {
    set_db(from.db());
  }
}

void struExample::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.struExample)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void struExample::CopyFrom(const struExample& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.struExample)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool struExample::IsInitialized() const {
  return true;
}

void struExample::Swap(struExample* other) {
  if (other == this) return;
  InternalSwap(other);
}
void struExample::InternalSwap(struExample* other) {
  using std::swap;
  str_.Swap(&other->str_);
  swap(id_, other->id_);
  swap(f_, other->f_);
  swap(db_, other->db_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata struExample::GetMetadata() const {
  protobuf_test1_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test1_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

struExamples_MEntry_DoNotUse::struExamples_MEntry_DoNotUse() {}
struExamples_MEntry_DoNotUse::struExamples_MEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void struExamples_MEntry_DoNotUse::MergeFrom(const struExamples_MEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata struExamples_MEntry_DoNotUse::GetMetadata() const {
  ::protobuf_test1_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test1_2eproto::file_level_metadata[1];
}
void struExamples_MEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void struExamples::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int struExamples::kVFieldNumber;
const int struExamples::kMFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

struExamples::struExamples()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_test1_2eproto::InitDefaultsstruExamples();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.struExamples)
}
struExamples::struExamples(const struExamples& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      v_(from.v_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  m_.MergeFrom(from.m_);
  // @@protoc_insertion_point(copy_constructor:test.struExamples)
}

void struExamples::SharedCtor() {
  _cached_size_ = 0;
}

struExamples::~struExamples() {
  // @@protoc_insertion_point(destructor:test.struExamples)
  SharedDtor();
}

void struExamples::SharedDtor() {
}

void struExamples::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* struExamples::descriptor() {
  ::protobuf_test1_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test1_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const struExamples& struExamples::default_instance() {
  ::protobuf_test1_2eproto::InitDefaultsstruExamples();
  return *internal_default_instance();
}

struExamples* struExamples::New(::google::protobuf::Arena* arena) const {
  struExamples* n = new struExamples;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void struExamples::Clear() {
// @@protoc_insertion_point(message_clear_start:test.struExamples)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  v_.Clear();
  m_.Clear();
  _internal_metadata_.Clear();
}

bool struExamples::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.struExamples)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .test.struExample v = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_v()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<int32, .test.struExample> m = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          struExamples_MEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              struExamples_MEntry_DoNotUse,
              ::google::protobuf::int32, ::test::struExample,
              ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample > > parser(&m_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.struExamples)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.struExamples)
  return false;
#undef DO_
}

void struExamples::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.struExamples)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .test.struExample v = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->v_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->v(static_cast<int>(i)), output);
  }

  // map<int32, .test.struExample> m = 2;
  if (!this->m().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterministic() &&
        this->m().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->m().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::const_iterator
          it = this->m().begin();
          it != this->m().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<struExamples_MEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(m_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
      }
    } else {
      ::google::protobuf::scoped_ptr<struExamples_MEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::const_iterator
          it = this->m().begin();
          it != this->m().end(); ++it) {
        entry.reset(m_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:test.struExamples)
}

::google::protobuf::uint8* struExamples::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:test.struExamples)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .test.struExample v = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->v_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->v(static_cast<int>(i)), deterministic, target);
  }

  // map<int32, .test.struExample> m = 2;
  if (!this->m().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->m().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->m().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::const_iterator
          it = this->m().begin();
          it != this->m().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<struExamples_MEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(m_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
      }
    } else {
      ::google::protobuf::scoped_ptr<struExamples_MEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::const_iterator
          it = this->m().begin();
          it != this->m().end(); ++it) {
        entry.reset(m_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.struExamples)
  return target;
}

size_t struExamples::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.struExamples)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .test.struExample v = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->v_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->v(static_cast<int>(i)));
    }
  }

  // map<int32, .test.struExample> m = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->m_size());
  {
    ::google::protobuf::scoped_ptr<struExamples_MEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::google::protobuf::int32, ::test::struExample >::const_iterator
        it = this->m().begin();
        it != this->m().end(); ++it) {
      entry.reset(m_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void struExamples::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.struExamples)
  GOOGLE_DCHECK_NE(&from, this);
  const struExamples* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const struExamples>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.struExamples)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.struExamples)
    MergeFrom(*source);
  }
}

void struExamples::MergeFrom(const struExamples& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.struExamples)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  v_.MergeFrom(from.v_);
  m_.MergeFrom(from.m_);
}

void struExamples::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.struExamples)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void struExamples::CopyFrom(const struExamples& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.struExamples)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool struExamples::IsInitialized() const {
  return true;
}

void struExamples::Swap(struExamples* other) {
  if (other == this) return;
  InternalSwap(other);
}
void struExamples::InternalSwap(struExamples* other) {
  using std::swap;
  v_.InternalSwap(&other->v_);
  m_.Swap(&other->m_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata struExamples::GetMetadata() const {
  protobuf_test1_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test1_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace test

// @@protoc_insertion_point(global_scope)
